import Head from "next/head";

const HTMLHeader = ({
  title = "SME Health - Get Started",
}: {
  title?: string;
}) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default HTMLHeader;
